"""
Django settings for django_examples project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from modal_2fa.settings_helper import modal_2fa_apps
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7mqe9(9$nxj&u88oc$6)7&tvid#1x1d#8txxvbt(d0r106%8w4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'backup_examples',
    'django_datatables',
    'django_modals',
    'crispy_forms',

    'ajax_helpers',
    'django_menus',
    'show_src_code',
    'cloud_backup',
    *modal_2fa_apps,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_examples.urls'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_examples.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': str(BASE_DIR.joinpath('db.sqlite3')),
#    }
#}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT', '5432')
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = False

USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

OTP_TOTP_ISSUER = 'backup'
AUTHENTICATION_BACKENDS = ['modal_2fa.auth.CookieBackend']
LOGIN_URL ='/auth/login/'
LOGOUT_REDIRECT_URL = '/auth/login'



OTP_TOTP_ISSUER = 'TEST 2FA'

CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False

DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ('%d/%m/%Y', '%Y-%m-%d', '%d-%m-%Y')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = '/media/'
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CREDENTIAL_FOLDER = os.path.join(BASE_DIR, '.credentials')
CREDENTIAL_FILES = {
    'drive': 'cred.json',
}

from encrypted_credentials.django_credentials import add_encrypted_settings

add_encrypted_settings(globals())
BACKUP_ROOT = 'test_backup'
BACKUP_ALLOW_RESTORE = True
# media/ at the repo root is mounted at /media by docker-compose; its test/
# sub-folder exercises the file browser's folder navigation
BACKUP_DIRS = [(MEDIA_ROOT, 'media')]
# Media kept in Azure Blob Storage instead (django-storages AzureStorage as the default
# storage): back up the container's media/ prefix through the same pipeline, into the
# same 'media' folder. The container and credentials come from the STORAGES / AZURE_*
# settings, or set AZURE_BACKUP_SOURCE = {'container': ..., 'connection_string': ...}
# AZURE_BACKUP_DIRS = [('media', 'media')]
BACKUP_DB_RETENTION = [{'hours': 1, 'number': 4},
                       {'hours': 2, 'number': 10},
                       {'days': 1, 'number': 10},
                       {'months': 1, 'number': 36},
                       ]
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

BACKUP_STORAGE = {
    'backend': 's3',
    'b2': True,
    'bucket': 'bucket',
    'access_key_id': access_key_id,       # B2 keyID
    'secret_key': secret_key,          # B2 applicationKey
    'root': 'test-backup'
}

# 'default' is everything above, unchanged - the web UI and un-parameterised tasks use it.
# 'database' sends the database dumps to a second bucket as well, with the lifecycle tiers
# (hourly/daily/monthly) so the bucket's own rules do the deleting instead of the
# application. The bucket has to exist first: open /backup/setup/ (or run
# manage.py storage_setup) for the b2 commands that create it with the right rules and an
# application key that cannot delete. B2 bucket names are globally unique, so change the
# name below if it is taken.
BACKUP_CONFIGS = {
    'default': {'storage' : BACKUP_STORAGE, 'db': False},
    'database': {
        'storage': dict(BACKUP_STORAGE, bucket='bucket-db', access_key_id=db_key_id, secret_key=db_key),
        'dirs': [],          # database only - the folder backups stay in the default bucket
        's3_dirs': [],
        # expire_days is what the lifecycle rules should say - the setup page generates
        # them and checks the bucket against them. monthly None keeps the end-of-month
        # dumps indefinitely; set 2557 for exactly 7 years.
        # To delete from the application instead of by bucket rules, and make the archive
        # immutable rather than merely un-ruled:
        #   'delete': 'app', 'lock_days': {'monthly': 2557}, 'lock_mode': 'COMPLIANCE'
        # (needs 'b2 bucket update --file-lock-enabled' once, and a key with deleteFiles)
        'db_tiers': {'expire_days': {'hourly': 15, 'daily': 91, 'monthly': None}},
        'retention': [],     # required with db_tiers: the lifecycle rules do the pruning
    },
}

# A third role for a staging server or a development machine: the destination another
# server backs up to, which this one only ever restores from. restore_only refuses every
# write to it, hides the backup buttons on its tab and makes the setup page generate a
# read-only key - which matters most when the machines share one encrypted settings file
# and therefore all hold the same credential:
# BACKUP_CONFIGS['live'] = {
#     'storage': dict(BACKUP_STORAGE, root='backup/live'),  # where the live server backs up
#     'restore_only': True,
#     'dirs': [],          # the database is what gets restored
#     's3_dirs': [],
# }
# Restore the latest live dump with: manage.py restore_db --config live

# Run it with: manage.py backup_website --db_only --config database
# Tier promotion happens at the end of every database backup, so the schedule below is a
# belt-and-braces second pass (it also covers days when no backup runs at all):
# CELERY_BEAT_SCHEDULE = {
#     'backup_database': {'task': 'cloud_backup.tasks.backup',
#                         'schedule': crontab(minute=10),
#                         'kwargs': {'config': 'database'}},
#     'promote_db_tiers': {'task': 'cloud_backup.tasks.promote_db_tiers',
#                          'schedule': crontab(hour=1, minute=30),
#                          'kwargs': {'config': 'database'}},
# }